apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argo-system
spec:
  parentRefs:
    - name: main
      namespace: kgateway-system
  hostnames:
    - dev.argocd.synapse.mabbott.dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: argo-system-argocd-server
          port: 80
