apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argo-events
  - argo-workflows
  - argocd
  - cert-manager
  - cloudnative-pg
  - crossplane
  - feast
  - flink
  - istio
  - kserve
  - kyverno
  - seaweedfs
  - strimzi
  - valkey
