---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: argo
spec:
  interval: 1h
  url: https://argoproj.github.io/argo-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
spec:
  interval: 30m
  targetNamespace: argo-system
  install:
    createNamespace: true
  kubeConfig:
    secretRef:
      name: cluster-kubeconfig
  chart:
    spec:
      chart: argo-cd
      version: "9.2.4"
      sourceRef:
        kind: HelmRepository
        name: argo
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: argocd-crossplane-health
  values:
    configs:
      cm:
        application.resourceTrackingMethod: annotation
        resource.exclusions: |
          - apiGroups:
              - "*"
            kinds:
              - ProviderConfigUsage
        accounts.crossplane: apiKey
      rbac:
        policy.csv: |
          p, role:crossplane, applications, *, */*, allow
          p, role:crossplane, projects, *, *, allow
          p, role:crossplane, repositories, *, *, allow
          g, crossplane, role:crossplane
      params:
        server.insecure: true
    controller:
      env:
        - name: ARGOCD_K8S_CLIENT_QPS
          value: "300"
    server:
      service:
        type: ClusterIP
