---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kgateway
spec:
  interval: 1h
  type: oci
  url: oci://cr.kgateway.dev/kgateway-dev/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway-crds
spec:
  interval: 30m
  targetNamespace: kgateway-system
  install:
    createNamespace: true
  kubeConfig:
    secretRef:
      name: cluster-kubeconfig
  chart:
    spec:
      chart: kgateway-crds
      version: "2.0.3"
      sourceRef:
        kind: HelmRepository
        name: kgateway
      interval: 12h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway
spec:
  dependsOn:
    - name: kgateway-crds
  interval: 30m
  targetNamespace: kgateway-system
  install:
    createNamespace: true
  kubeConfig:
    secretRef:
      name: cluster-kubeconfig
  chart:
    spec:
      chart: kgateway
      version: "2.0.3"
      sourceRef:
        kind: HelmRepository
        name: kgateway
      interval: 12h
