apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ${TENANT_NAME}-apps
  namespace: argo-system
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=zero"]
  generators:
    - git:
        repoURL: ${TENANT_REPO_URL}
        revision: ${TENANT_REVISION}
        files:
          - path: ${TENANT_APP_DISCOVERY_PATH}
  template:
    metadata:
      name: '{{.name}}-${TENANT_ENV}'
      labels:
        tenant: ${TENANT_NAME}
        team: '{{.team}}'
    spec:
      project: ${TENANT_NAME}
      source:
        repoURL: ${TENANT_REPO_URL}
        targetRevision: ${TENANT_REVISION}
        path: '{{ if .sourcePath }}{{.sourcePath}}{{ else }}apps/{{.name}}/deploy/overlays/${TENANT_ENV}{{ end }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ if .targetNamespace }}{{.targetNamespace}}{{ else }}{{.name}}{{ end }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
