apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - disallow-privileged-containers.yaml
  - disallow-host-namespaces.yaml
  - disallow-host-path.yaml
  - require-run-as-non-root.yaml
  - disallow-privilege-escalation.yaml
  - require-seccomp-profile.yaml
