---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
spec:
  package: xpkg.crossplane.io/crossplane-contrib/provider-kubernetes:v1.2.0
  runtimeConfigRef:
    name: provider-kubernetes
---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-management
spec:
  package: ghcr.io/mdaops/cortex/configuration-management:latest
