apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: synapse-gateway
  namespace: kgateway-system
spec:
  secretName: synapse-gateway-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - dev.argocd.synapse.mabbott.dev
    - "*.synapse.mabbott.dev"
  issuerRef:
    name: synapse-gateway-ca
    kind: ClusterIssuer
