apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ${TENANT_NAME}-apps
  namespace: argo-system
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: ${TENANT_REPO_URL}
        revision: ${TENANT_REVISION}
        files:
          - path: ${TENANT_APP_DISCOVERY_PATH}
  template:
    metadata:
      name: '{{.name}}-${TENANT_ENV}'
      labels:
        tenant: ${TENANT_NAME}
        team: '{{.team}}'
    spec:
      project: ${TENANT_NAME}
      source:
        repoURL: ${TENANT_REPO_URL}
        targetRevision: ${TENANT_REVISION}
        path: '{{.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
