apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ${TENANT_NAME}
  namespace: argo-system
spec:
  description: ${TENANT_NAME} product workloads
  sourceRepos:
    - ${TENANT_REPO_URL}
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
